/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uts;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.DriverManager;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author bachtiar
 */
public class Uts extends javax.swing.JFrame {
      private final String[] columns = {"ISBN", "Judul Buku", "Tahun Penerbit","Penerbit"};
    private final ArrayList<String[]> dataList = new ArrayList<>();
    Connection conn;

    String driver = "org.postgresql.Driver";
    String koneksi = "jdbc:postgresql://localhost:5432/Uts";
    String user = "postgres";
    String password = "yarde";

    
    
   public final void getAllData() {
        try {
            dataList.clear();
            String sql = "SELECT * FROM buku";
            conn = DriverManager.getConnection(koneksi, user, password);
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.executeQuery();
            final ResultSet data = ps.getResultSet();
            while (data.next()) {
                final String[] row = new String[]{
                    data.getString("ISBN"),
                    data.getString("judul_buku"),
                    data.getString("tahun_terbit"),
                    data.getString("penerbit")};
                dataList.add(row);
            }
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }

    public final void refreshModel() {
        DefaultTableModel model = new DefaultTableModel();
        model.setColumnIdentifiers(columns);
        for (String[] data : dataList) {
            model.addRow(data);
        }
        table.setModel(model);
    }

    /**
     * Creates new form Uts
     */
    public Uts() {
        initComponents();
        this.getAllData();
        this.refreshModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        isbnLbl = new javax.swing.JLabel();
        tahunLbl = new javax.swing.JLabel();
        judulLbl = new javax.swing.JLabel();
        penerbitLbl = new javax.swing.JLabel();
        judulTxt = new javax.swing.JTextField();
        tahunTxt = new javax.swing.JTextField();
        penerbitTxt = new javax.swing.JTextField();
        isbnTxt = new javax.swing.JTextField();
        updateBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        clearBtn = new javax.swing.JButton();
        insertBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("NSimSun", 1, 36)); // NOI18N
        jLabel1.setText("BUKU");

        isbnLbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        isbnLbl.setText("ISBN");

        tahunLbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tahunLbl.setText("Tahun Terbit");

        judulLbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        judulLbl.setText("Judul Buku");

        penerbitLbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        penerbitLbl.setText("Penerbit");

        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        clearBtn.setText("Clear");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });

        insertBtn.setText("Insert");
        insertBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertBtnActionPerformed(evt);
            }
        });

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(judulLbl)
                            .addComponent(tahunLbl)
                            .addComponent(penerbitLbl)
                            .addComponent(isbnLbl))
                        .addGap(87, 87, 87)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(judulTxt)
                            .addComponent(isbnTxt)
                            .addComponent(tahunTxt)
                            .addComponent(penerbitTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(insertBtn)
                        .addGap(28, 28, 28)
                        .addComponent(updateBtn)
                        .addGap(35, 35, 35)
                        .addComponent(deleteBtn)
                        .addGap(45, 45, 45)
                        .addComponent(clearBtn)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(isbnTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(isbnLbl))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(judulTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(judulLbl))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tahunLbl)
                            .addComponent(tahunTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(penerbitTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(penerbitLbl)))
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(updateBtn)
                            .addComponent(deleteBtn)
                            .addComponent(clearBtn)
                            .addComponent(insertBtn)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
         isbnTxt.setText("");
                    judulTxt.setText("");
                    tahunTxt.setText("");
                    penerbitTxt.setText("");
    }//GEN-LAST:event_clearBtnActionPerformed

    private void insertBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertBtnActionPerformed
       String isbn = isbnTxt.getText();
        String judul = judulTxt.getText();
        String tahun = tahunTxt.getText();
        String penerbit = penerbitTxt.getText();
        if (isbn.trim().isEmpty() && judul.trim().isEmpty() && tahun.trim().isEmpty()&&penerbit.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "masukan data anda terlebih dahulu");

        } else if (isbn.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "masukan isbn anda terlebih dahulu");
        } else if (judul.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "masukan judul anda terlebih dahulu");
        } else if (tahun.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "masukan tahun anda terlebih dahulu");
        }else if (penerbit.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "masukkan penerbit anda terlebih dahulu");
        }
        else {
            PreparedStatement preparedStatement;
            try {
                String sql = "INSERT INTO buku (isbn, judul_buku, tahun_terbit,penerbit) VALUES (?, ?, ?, ?)";

                preparedStatement = conn.prepareStatement(sql);

                preparedStatement.setString(1, isbn);
                preparedStatement.setString(2, judul);
                preparedStatement.setString(3, tahun);
                preparedStatement.setString(4, penerbit);

                preparedStatement.executeUpdate();
                this.getAllData();
                this.refreshModel();
                JOptionPane.showMessageDialog(this, "data berhasil ditambahkan");

            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Gagal abangkuh", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_insertBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
         Statement statement;
        String isbn = isbnTxt.getText();
        if (isbn.trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Error abangkuh", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            try {
                String query = String.format("Delete from buku where isbn ='%s'", isbn);
                statement = conn.createStatement();
                statement.executeUpdate(query);
                JOptionPane.showMessageDialog(this, "data berhasil dihapus");
                this.getAllData();
                this.refreshModel();
            } catch (SQLException e) {

                JOptionPane.showMessageDialog(this, "data gagal dihapus");
                System.out.println(e.getMessage());
            }
        }
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
          String isbn = isbnTxt.getText();
        String judul = judulTxt.getText();
        String tahun = tahunTxt.getText();
        String penerbit = penerbitTxt.getText();
        
        if (isbn.trim().isEmpty() && judul.trim().isEmpty() && tahun.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "masukan data anda terlebih dahulu");

        } else if (isbn.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "masukan isbn anda terlebih dahulu");
        } else if (judul.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "masukan judul anda terlebih dahulu");
        } else if (tahun.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "masukan tahun anda terlebih dahulu");
        } else {
            try {
                String sql = "update buku set judul_buku =?,  tahun_terbit = ?,penerbit = ? where isbn = ?";
                PreparedStatement ps = conn.prepareStatement(sql);
                ps.setString(1, judul);
                ps.setString(2, tahun);
                ps.setString(3, penerbit);
                ps.setString(4, isbn);
                int row = ps.executeUpdate();
                if (row > 0) {
                    JOptionPane.showMessageDialog(this, "Update Berhasil");
                    this.getAllData();
                    this.refreshModel();
                    isbnTxt.setText("");
                    judulTxt.setText("");
                    tahunTxt.setText("");
                    penerbitTxt.setText("");
                }

            } catch (Exception e) {
                System.out.println(e.getMessage());
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        }
    }//GEN-LAST:event_updateBtnActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        int selectedRow = table.getSelectedRow();
        if (selectedRow != -1) {
            String isbn = table.getValueAt(selectedRow, 0).toString();
            String judul = table.getValueAt(selectedRow, 1).toString();
            String tahun = table.getValueAt(selectedRow, 2).toString();
            String penerbit = table.getValueAt(selectedRow, 3).toString();

            isbnTxt.setText(isbn);
            judulTxt.setText(judul);
            tahunTxt.setText(tahun);
            penerbitTxt.setText(penerbit);
        }        
    }//GEN-LAST:event_tableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Uts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Uts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Uts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Uts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Uts().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearBtn;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JButton insertBtn;
    private javax.swing.JLabel isbnLbl;
    private javax.swing.JTextField isbnTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel judulLbl;
    private javax.swing.JTextField judulTxt;
    private javax.swing.JLabel penerbitLbl;
    private javax.swing.JTextField penerbitTxt;
    private javax.swing.JTable table;
    private javax.swing.JLabel tahunLbl;
    private javax.swing.JTextField tahunTxt;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
