/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UasPBO;

//import java.awt.List;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.util.List;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JProgressBar;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import javax.swing.filechooser.FileSystemView;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author bachtiar
 */
public class Utama extends javax.swing.JFrame {

    private final String[] columns = {"Kode Mk", "sks", "nama mata kuliah", "semester ajar"};
    private final ArrayList<String[]> dataList = new ArrayList<>();
    Connection conn;
    Mahasiswa m = new Mahasiswa();
    EntityManagerFactory emf = Persistence.createEntityManagerFactory("pboPU");
    EntityManager em = emf.createEntityManager();

    public void tampilPU() {
        em = emf.createEntityManager();

        try {
            DefaultTableModel tbnmhs = new DefaultTableModel(new String[]{"NIM", "Nama", "Alamat", "Asal SMA", "Nama Orang Tua"}, 0);

            List<Mahasiswa> mahasiswaList = em.createNamedQuery("Mahasiswa.findAll", Mahasiswa.class).getResultList();

            for (Mahasiswa mk : mahasiswaList) {
                tbnmhs.addRow(new Object[]{
                    mk.getNim(),
                    mk.getNama(),
                    mk.getAlamat(),
                    mk.getAsalsma(),
                    mk.getNamaorangtua()
                });
            }

            table.setModel(tbnmhs);
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
    }

    public final void refreshModel() {
        DefaultTableModel model = new DefaultTableModel();
        model.setColumnIdentifiers(columns);
        for (String[] data : dataList) {
            model.addRow(data);
        }
        table.setModel(model);
    }

    /**
     * Creates new form Uts
     */
    public Utama() {
        initComponents();
        String driver = "org.postgresql.Driver";
        String koneksi = "jdbc:postgresql://localhost:5432/UTSPBO";
        String user = "postgres";
        String password = "yarde";
        try {
            conn = DriverManager.getConnection(koneksi, user, password);

        } catch (SQLException e) {
        }
//        tampilPU();
//        this.refreshModel();
        tampilPU();

        updateBtn.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        isbnLbl = new javax.swing.JLabel();
        tahunLbl = new javax.swing.JLabel();
        judulLbl = new javax.swing.JLabel();
        penerbitLbl = new javax.swing.JLabel();
        namaTxt = new javax.swing.JTextField();
        alamatTxt = new javax.swing.JTextField();
        asalSma = new javax.swing.JTextField();
        nimTxt = new javax.swing.JTextField();
        updateBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        clearBtn = new javax.swing.JButton();
        insertBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        namaortuTXT = new javax.swing.JTextField();
        penerbitLbl1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("NSimSun", 1, 36)); // NOI18N
        jLabel1.setText("MAHASISWA");

        isbnLbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        isbnLbl.setText("NIM");

        tahunLbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tahunLbl.setText("Alamat");

        judulLbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        judulLbl.setText("Nama");

        penerbitLbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        penerbitLbl.setText("Asal SMA");

        alamatTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alamatTxtActionPerformed(evt);
            }
        });

        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        clearBtn.setText("Clear");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });

        insertBtn.setText("Insert");
        insertBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertBtnActionPerformed(evt);
            }
        });

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        jButton1.setText("Cetak");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Upload");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        penerbitLbl1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        penerbitLbl1.setText("Nama Orang Tua");

        jButton3.setText("Logout");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(judulLbl)
                            .addComponent(tahunLbl)
                            .addComponent(penerbitLbl)
                            .addComponent(isbnLbl)
                            .addComponent(penerbitLbl1))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(namaortuTXT)
                            .addComponent(namaTxt)
                            .addComponent(nimTxt)
                            .addComponent(alamatTxt)
                            .addComponent(asalSma)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(insertBtn)
                            .addComponent(jButton1))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(updateBtn)
                            .addComponent(jButton2))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(deleteBtn)
                                .addGap(45, 45, 45)
                                .addComponent(clearBtn))
                            .addComponent(jButton3))))
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(nimTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(isbnLbl))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(namaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(judulLbl))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tahunLbl)
                            .addComponent(alamatTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(asalSma, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(penerbitLbl)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(namaortuTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(penerbitLbl1)))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(updateBtn)
                            .addComponent(deleteBtn)
                            .addComponent(clearBtn)
                            .addComponent(insertBtn))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2)
                            .addComponent(jButton3))))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        nimTxt.setText("");
        namaTxt.setText("");
        alamatTxt.setText("");
        asalSma.setText("");
        namaortuTXT.setText("");
        nimTxt.setEditable(true);
        updateBtn.setEnabled(false);
    }//GEN-LAST:event_clearBtnActionPerformed

    private void insertBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertBtnActionPerformed
        String nim = nimTxt.getText();
        String nama = namaTxt.getText();
        String alamat = alamatTxt.getText();
        String asalsma = asalSma.getText();
        String namaortu = namaortuTXT.getText();
        if (nim.trim().isEmpty() && nama.trim().isEmpty() && alamat.trim().isEmpty() && asalsma.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "masukan data anda terlebih dahulu");

        } else if (nim.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "masukan nim terlebih dahulu");
        } else if (nama.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "masukan nama terlebih dahulu");
        } else if (alamat.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "masukan alamat terlebih dahulu");
        } else if (asalsma.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "masukkan asal sma terlebih dahulu");
        } else if (namaortu.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "masukan nama orang tua terlebih dahulu");
        } else {
            em.getTransaction().begin();
            m.setNim(nimTxt.getText());
            m.setNama(namaTxt.getText());
            m.setAsalsma(asalSma.getText());
            m.setAlamat(alamatTxt.getText());
            m.setNamaorangtua(namaortuTXT.getText());
            em.persist(m);
            em.getTransaction().commit();

            JOptionPane.showMessageDialog(this, "data berhasil ditambahkan");
            tampilPU();

            nimTxt.setText("");
            namaTxt.setText("");
            alamatTxt.setText("");
            asalSma.setText("");
            namaortuTXT.setText("");
            nimTxt.setEditable(true);
            updateBtn.setEnabled(false);

        }
    }//GEN-LAST:event_insertBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed

        String nim = nimTxt.getText();
        if (nim.trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Error abangkuh", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            em.getTransaction().begin();

            m = em.find(Mahasiswa.class, nimTxt.getText());
            em.remove(m);
            em.getTransaction().commit();
            JOptionPane.showMessageDialog(this, "data berhasil dihapus");
            tampilPU();
            nimTxt.setText("");
            namaTxt.setText("");
            alamatTxt.setText("");
            asalSma.setText("");
            namaortuTXT.setText("");
            nimTxt.setEditable(true);
            updateBtn.setEnabled(false);

        }
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        String NIM = nimTxt.getText();
        String Nama = namaTxt.getText();
        String Alamat = alamatTxt.getText();
        String asal = asalSma.getText();

        if (NIM.trim().isEmpty() && Nama.trim().isEmpty() && Alamat.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "masukan data anda terlebih dahulu");

        } else if (NIM.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "masukan NIM anda terlebih dahulu");
        } else if (Nama.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "masukan Nama anda terlebih dahulu");
        } else if (Alamat.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "masukan Alamat anda terlebih dahulu");
        } else {
            em.getTransaction().begin();

            m = em.find(Mahasiswa.class, nimTxt.getText());

            m.setNim(nimTxt.getText());
            m.setNama(namaTxt.getText());
            m.setAlamat(alamatTxt.getText());
            m.setAsalsma(asalSma.getText());
            m.setNamaorangtua(namaortuTXT.getText());
            em.persist(m);

            em.getTransaction().commit();

            JOptionPane.showMessageDialog(this, "Update Berhasil");
            tampilPU();
            nimTxt.setText("");
            namaTxt.setText("");
            alamatTxt.setText("");
            asalSma.setText("");
            namaortuTXT.setText("");
            nimTxt.setEditable(true);
            updateBtn.setEnabled(false);

        }
    }//GEN-LAST:event_updateBtnActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        int selectedRow = table.getSelectedRow();
        if (selectedRow != -1) {
            String isbn = table.getValueAt(selectedRow, 0).toString();
            String judul = table.getValueAt(selectedRow, 1).toString();
            String tahun = table.getValueAt(selectedRow, 2).toString();
            String asal = table.getValueAt(selectedRow, 3).toString();
            String namaortu = table.getValueAt(selectedRow, 4).toString();

            nimTxt.setText(isbn);
            nimTxt.setEditable(false);
            namaTxt.setText(judul);
            alamatTxt.setText(tahun);
            asalSma.setText(asal);
            namaortuTXT.setText(namaortu);
            updateBtn.setEnabled(true);
        }
    }//GEN-LAST:event_tableMouseClicked

    private void alamatTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alamatTxtActionPerformed
    }//GEN-LAST:event_alamatTxtActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            JasperReport reports;
            String path = "src\\UASPBO\\report1.jasper";
            reports = (JasperReport) JRLoader.loadObjectFromFile(path);
            JasperPrint print = JasperFillManager.fillReport(path, null, conn);
            JasperViewer view = new JasperViewer(print, false);
            view.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            view.setVisible(true);
            nimTxt.setText("");
            namaTxt.setText("");
            alamatTxt.setText("");
            asalSma.setText("");
            nimTxt.setEditable(true);
        } catch (JRException e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        JFileChooser jfc = new JFileChooser(FileSystemView.getFileSystemView().getHomeDirectory());
        int returnValue = jfc.showOpenDialog(null);
        if (returnValue == JFileChooser.APPROVE_OPTION) {
            File filePilihan = jfc.getSelectedFile();
            System.out.println("yang dipilih : " + filePilihan.getAbsolutePath());
            try {
                BufferedReader br = new BufferedReader(new FileReader(filePilihan));
                String baris = new String("");
                String pemisah = ",";
                while ((baris = br.readLine()) != null) //returns a Boolean value
                {
                    String[] dataMhs = baris.split(pemisah);
                    String Nim = dataMhs[0];
                    String nama = dataMhs[1];
                    String alamat = dataMhs[2];
                    String asal = dataMhs[3];
                    String namaortu = dataMhs[4];

                    if (!Nim.isEmpty() && !asal.isEmpty() && !nama.isEmpty() && !alamat.isEmpty()) {
                        em.getTransaction().begin();
                        m.setNim(Nim);
                        m.setNama(nama);
                        m.setAlamat(alamat);
                        m.setAsalsma(asal);
                        m.setNamaorangtua(namaortu);
                        em.persist(m);
                        em.getTransaction().commit();
                        JOptionPane.showMessageDialog(this, "data berhasil ditambahkan");

                        tampilPU();
                    }
                }
            } catch (FileNotFoundException ex) {
            } catch (IOException ex) {
            }
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Login f = new Login();
        f.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Utama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alamatTxt;
    private javax.swing.JTextField asalSma;
    private javax.swing.JButton clearBtn;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JButton insertBtn;
    private javax.swing.JLabel isbnLbl;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel judulLbl;
    private javax.swing.JTextField namaTxt;
    private javax.swing.JTextField namaortuTXT;
    private javax.swing.JTextField nimTxt;
    private javax.swing.JLabel penerbitLbl;
    private javax.swing.JLabel penerbitLbl1;
    private javax.swing.JTable table;
    private javax.swing.JLabel tahunLbl;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
